In [ ]:
# NumPy 기초 정리

# 파이썬 데이터 분석의 핵심 라이브러리인 **NumPy**의 기초 개념을 실습 중심으로 정리한 노트입니다.

## 학습 목표
#- ndarray 구조 이해
#- 배열 생성 방법 숙지
#- dtype 개념 이해
#- 인덱싱 & 슬라이싱
#- 브로드캐스팅 원리 이해
#- 집계 함수와 axis 개념 이해
#- reshape / transpose 구조 변환

In [4]:
# 넘파이 사용하기
import numpy as np

In [5]:
print(np.array([1,2,3]))  # 배열 : array

[1 2 3]


In [6]:
import numpy
print(numpy.array([1,2,3]))

[1 2 3]


In [7]:
# 넘파이 배열, ndarray
# 1차 배열 알아보기
import numpy as np
arr_1=np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [8]:
[1,2,3,4,5]*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
arr_1*2

array([ 2,  4,  6,  8, 10])

In [10]:
# 2차 배열 알아보기
arr_2 =np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]]
) # 파이선 리스트를 ndarray로 변환
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# 3차원 배열 알아보기
# 3차원 배열은 가로, 세로, 높이를 가지는 정육면체로 나타낼 수 있습니다.
import numpy as np
arr_3 = np.array([[[1,2,3],
                   [4,5,6]],
                   [[7,8,9],
                    [10,11,12]],
                  [[13,14,15],
                   [16,17,18]]]) # 파이썬 리스트를 넘파이 배열로 변환
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [14]:
# 넘파이 배열의 데이터 타입 살펴보기
import numpy as np
arr_1=np.array([1,2,3,4,5])
print(arr_1.dtype)

int64


In [ ]:
# 결과값을 보면 int64|int는 정수 64는 컴퓨터 공학지식으로 설명하면 int64는 64비트로 표현한 정수라고 할 수 잇다.

In [15]:
# 데이터 타입 확인해보기
import numpy as np
print(np.array([1,2,3]).dtype)

int64


In [16]:
print(np.array([1,2,3],dtype='int8').dtype)

int8


In [17]:
print(np.array([1,2,3],dtype='i1').dtype)

int8


In [19]:
# 넘파이 배열의 장점 알아보기
import numpy as np
ndarray_1 = np.array([1,2,3]) # 넘파이 배열
ndarray_2 = np.array([4,5,6]) # 넘파이 배열
list_1=[1,2,3] # 파이썬 리스트
list_2=[4,5,6] # 파이썬 리스트

In [20]:
print(ndarray_1+ndarray_2)
print(list_1+list_2)

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [21]:
raise_list=[x+y for x,y in zip(list_1,list_2)]
print(raise_list)

[5, 7, 9]


In [22]:
print(ndarray_1*2)
print(list_1*2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [23]:
# 다양한 방법으로 넘파이 배열 생성하기
import numpy as np
a=np.array([2,3,4]) # 넘파이 정수형 배열 생성
print(a) # 넘파이 배열 출력
print(a.dtype) # 넘파이 배열의 데이터 타입 출력
b = np.array([2.1,3.2,4.3]) # 넘파이 실수형 배열 생성
print(b)
print(b.dtype)

[2 3 4]
int64
[2.1 3.2 4.3]
float64


In [24]:
# 파이썬 튜플로 넘파이 배열 생성하기
c =np.array(('i','j','k'))  # 넘파이 문자열 배열 생성
print(c)
print(c.dtype)

['i' 'j' 'k']
<U1


In [25]:
d =np.array((True,False,True)) # 넘파이 논리형 배열 생성
print(d)
print(d.dtype)

[ True False  True]
bool


In [26]:
e=np.array(['ab','cd','e'],dtype='<U2') # 문자열 길이를 조절하여 배열 생성
print(e)
print(e.dtype)

['ab' 'cd' 'e']
<U2


In [27]:
# 넘파이 배열 속성 이해하고 출력해보기
import numpy as np
a= np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
print(a.shape) # 배열의 차원과 차원의 크리 반환
print(a.ndim) #배열의 차원 수 반환
print(a.dtype) # 배열의 데이터 타입 반환
print(a.itemsize) # 배열의 각 요소의 크리극 바이트 단위로 반환
print(a.size) # 배열의 총 요소의 수 반환

(3, 4)
2
int64
8
12


In [ ]:
# 넘파이 3차원 배열 생성해보기

In [31]:
import numpy as np

# 각 학급에 3명의 학생, 각 학생이 3과목의 시험점수를 가지고 있는 배열 생성
# 예시 : 3개의 학급, 각 학습에 3명의 학생, 각 학생 당 국거, 영어, 수학 점수
scores =np.random.randint(0,101,size=(3,4,3))

# 학급별, 학생별, 과목별 점수를 출력
print("학급별 학생들의 점수 배열(3차원 배열):")
print(scores)
# 학급, 학생, 과목별로 점수 출력

for class_idx in range(scores.shape[0]):
    print(f"\nClass: {class_idx+1}")
    for student_idx in range(scores.shape[1]):
        korean,english,math=scores[class_idx,student_idx]
        print(f"Student {student_idx+1}-Korean:{korean}-English:{english}-Math:{math}")

학급별 학생들의 점수 배열(3차원 배열):
[[[67 40  8]
  [11 28 93]
  [46 99 33]
  [19 93 68]]

 [[33 79  9]
  [77  6 93]
  [ 1 57 34]
  [13 86 31]]

 [[81  5 55]
  [20 59  1]
  [18 38 15]
  [10 67 76]]]

Class: 1
Student 1-Korean:67-English:40-Math:8
Student 2-Korean:11-English:28-Math:93
Student 3-Korean:46-English:99-Math:33
Student 4-Korean:19-English:93-Math:68

Class: 2
Student 1-Korean:33-English:79-Math:9
Student 2-Korean:77-English:6-Math:93
Student 3-Korean:1-English:57-Math:34
Student 4-Korean:13-English:86-Math:31

Class: 3
Student 1-Korean:81-English:5-Math:55
Student 2-Korean:20-English:59-Math:1
Student 3-Korean:18-English:38-Math:15
Student 4-Korean:10-English:67-Math:76


In [33]:
# 초기화ㅏ 함수로 넘파이 배열 생성하기
import numpy as np
print(np.zeros((3,4)))
print(np.zeros((3,4),dtype=int))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [34]:
# (2,3,4) 크기의 배열을 생성하여 데이터 타입을 정수로 설정한 후, 1로 채움
print(np.ones((2,3,4),dtype=int))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [35]:
print(np.empty((2,3)))

[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]


In [36]:
print(np.arange(10,30,5))
print(np.arange(start = 0,stop =2,step =0.3))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [37]:
print(np.linspace(start=1,stop=10,num=10,dtype=int))

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
# 넘파이 배열로 다양하게 연산하기
# 요소별 연산하기
# 요소별 연산으로 사칙연산하기

a=np.array([10,20,30,40])
b=np.arange(start = 1,stop=5)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[10 20 30 40]
[1 2 3 4]
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [40]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

print(A*B)
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [41]:
A=np.array([1,2,3,4])
B=np.array([1,1,3,3])

print(A>B)
print(A==B)

[False  True False  True]
[ True False  True False]


In [42]:
student1_scores=np.array([85,90,78])
student2_scores=np.array([92,88,95])
print("학생 1의 점수:",student1_scores)
print("학생 2의 점수:",student2_scores)
total_scores =student1_scores+student2_scores
print("두 학생의 총점:",total_scores)
avg_scores=total_scores/2
print("두 학생의 평균 점수:",avg_scores)
student1_total=np.sum(student1_scores)
student2_total=np.sum(student2_scores)
student1_avg=np.mean(student1_scores)
student2_avg=np.mean(student2_scores)

print("학생 1의 총점:",student1_total)
print("학생 1의 평균 점수:",student1_avg)
print("학생 2의 총점:",student2_total)
print("학생 2의 평균 점수:",student2_avg)

학생 1의 점수: [85 90 78]
학생 2의 점수: [92 88 95]
두 학생의 총점: [177 178 173]
두 학생의 평균 점수: [88.5 89.  86.5]
학생 1의 총점: 253
학생 1의 평균 점수: 84.33333333333333
학생 2의 총점: 275
학생 2의 평균 점수: 91.66666666666667


In [43]:
A=np.array([4,16,25])
print(np.sqrt(A))

[2. 4. 5.]


In [46]:
a = np.arange(8).reshape(2,4)**2
print(a)

print(a.sum())
print(a.mean())
print(a.max())
print(a.cumsum())
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
140
17.5
49
[  0   1   5  14  30  55  91 140]
7


In [47]:
a =np.arange(8).reshape(2,4)**2
print(a.mean(axis=0))
print(a.max(axis=1))


[ 8. 13. 20. 29.]
[ 9 49]


In [49]:
a = np.array([0,1,2,3,4,5])
print(a)
print(a[0])
print(a[3])

[0 1 2 3 4 5]
0
3


In [50]:
b =np.array([[0,1,2],[3,4,5]])
print(b)

print(b[1,0])
print(b[1,2])

[[0 1 2]
 [3 4 5]]
3
5


In [51]:
a =np.array([0,1,2,3,4,5])
print(a)
print(a[0:3])

[0 1 2 3 4 5]
[0 1 2]


In [52]:
a=np.arange(12).reshape(3,4)
print(a)

b=a>4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [53]:
print(a[b])
print(a[b].shape)

[ 5  6  7  8  9 10 11]
(7,)


In [54]:
a[b] =1000
print(a)

[[   0    1    2    3]
 [   4 1000 1000 1000]
 [1000 1000 1000 1000]]


In [55]:
a = np.array(['a','b','c','d','e','f','g','h'])
i = np.array([1,1,3,4])

print(a[i])
j = np.array([[3,4],[5,6]])

print(a[j])

['b' 'b' 'd' 'e']
[['d' 'e']
 ['f' 'g']]


In [56]:
b =np.array(['a','b','c','d'])
k =np.array([3,2,1,0])

b = b[k]
print(b)

['d' 'c' 'b' 'a']


In [57]:
my_list =[10,20,30,40,50]
subset =my_list[1:4]
print(subset)

[20, 30, 40]


In [1]:
import numpy as np

# a 배열 생성
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)
print(a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2


In [3]:
# reshape : 지정한 차원으로 변경하고 새로운 배열 반환
b = a.reshape(2,6)
print(b)
print(b.shape)
print(a)
print(a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [4]:
c =a.reshape(-1,3)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
import numpy as np
a =np.arange(12)
a.resize(4,3)
print(a)
print(a.shape)
print(a.resize(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
None


In [6]:
a = np.arange(12).reshape(3,4)
print(a.ravel())
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
A = np.arange(12).reshape(2,6)
print(A)

print(A.T)
print(A.T.shape)

A=A.T
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]
(6, 2)


In [8]:
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
a =np.arange(12).reshape(2,6)
print(a)

print(np.vsplit(a,2))
print(np.hsplit(a,3))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10, 11]])]
[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
